import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  // English
  en: {
    dashboard: 'Dashboard',
    welcome: 'Welcome back',
    availableOrders: 'Available Orders',
    myOrders: 'My Orders',
    statistics: 'Statistics',
    profile: 'Profile',
    logout: 'Logout',
    orderNumber: 'Order #',
    status: 'Status',
    seller: 'Seller',
    rider: 'Rider',
    fee: 'Fee',
    distance: 'Distance',
    actions: 'Actions',
    accept: 'Accept',
    chat: 'Chat',
    track: 'Track',
    pending: 'Pending',
    accepted: 'Accepted',
    inTransit: 'In Transit',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    totalOrders: 'Total Orders',
    completedOrders: 'Completed Orders',
    averageRating: 'Average Rating',
    earnings: 'Total Earnings',
    availability: 'Availability',
    available: 'Available',
    unavailable: 'Unavailable',
    pickupLocation: 'Pickup Location',
    deliveryLocation: 'Delivery Location',
    packageDescription: 'Package Description',
    packageWeight: 'Package Weight',
    deliveryFee: 'Delivery Fee',
    priority: 'Priority',
    paymentMethod: 'Payment Method',
    specialInstructions: 'Special Instructions',
    standard: 'Standard',
    express: 'Express',
    urgent: 'Urgent',
    cash: 'Cash',
    mpesa: 'M-Pesa',
    card: 'Card',
    motorcycle: 'Motorcycle',
    driver: 'Driver',
    vehicleNumber: 'Vehicle Number',
    serviceArea: 'Service Area',
    averageRating: 'Average Rating',
    totalRatings: 'Total Ratings',
    credibilityScore: 'Credibility Score',
    completedDeliveries: 'Completed Deliveries',
    totalEarnings: 'Total Earnings',
    online: 'Online',
    offline: 'Offline',
    lastSeen: 'Last Seen',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    userType: 'User Type',
    businessName: 'Business Name',
    businessLocation: 'Business Location',
    riderType: 'Rider Type',
    area: 'Area',
    changePassword: 'Change Password',
    changeLanguage: 'Change Language',
    editProfile: 'Edit Profile',
    notifications: 'Notifications',
    settings: 'Settings',
    help: 'Help',
    about: 'About',
    contact: 'Contact',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service'
  },

  // Kiswahili
  sw: {
    dashboard: 'Dashibodi',
    welcome: 'Karibu tena',
    availableOrders: 'Oda Zilizopo',
    myOrders: 'Oda Zangu',
    statistics: 'Takwimu',
    profile: 'Wasifu',
    logout: 'Toka',
    orderNumber: 'Namba ya Oda',
    status: 'Hali',
    seller: 'Muuza',
    rider: 'Mpanda baiskeli',
    fee: 'Ada',
    distance: 'Umbali',
    actions: 'Matendo',
    accept: 'Kubali',
    chat: 'Mazungumzo',
    track: 'Kufuatilia',
    pending: 'Inasubiri',
    accepted: 'Imekubali',
    inTransit: 'Inaendelea',
    delivered: 'Imewasilishwa',
    cancelled: 'Imefunguliwa',
    totalOrders: 'Jumla ya Oda',
    completedOrders: 'Oda Zilizopo Zilizopo',
    averageRating: 'Wastani wa Wastani',
    earnings: 'Mapato',
    availability: 'Uwezekaji',
    available: 'Yupo',
    unavailable: 'Hayupo',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya Kifurushi',
    packageWeight: 'Uzito wa Kifurushi',
    deliveryFee: 'Ada ya Kuleta',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya Malipo',
    specialInstructions: 'Maagizo ya Ziada',
    standard: 'Ya Kawaida',
    express: 'Ya Haraka',
    urgent: 'Ya Dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Pikipiki',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya Gari',
    serviceArea: 'Eneo la Huduma',
    averageRating: 'Wastani wa Wastani',
    totalRatings: 'Jumla ya Wastani',
    credibilityScore: 'Alama ya Uaminifu',
    completedDeliveries: 'Oda Zilizopo Zilizopo',
    totalEarnings: 'Mapato',
    online: 'Yupo Mtandaoni',
    offline: 'Hayupo Mtandaoni',
    lastSeen: 'Ulionekewa Mwisho',
    name: 'Jina',
    email: 'Barua Pepe',
    phone: 'Namba ya Simu',
    userType: 'Aina ya Mtumia',
    businessName: 'Jina la Biashara',
    businessLocation: 'Eneo la Biashara',
    riderType: 'Aina ya Mpanda',
    area: 'Eneo la Huduma',
    changePassword: 'Badilisha Nenosiri',
    changeLanguage: 'Badilisha Lugha',
    editProfile: 'Hariri Wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya Faragha',
    terms: 'Masharti ya Huduma'
  },

  // Kikuyu
  ki: {
    dashboard: 'Orora',
    welcome: 'Nwari',
    availableOrders: 'Oda Ahari',
    myOrders: 'Oda Angu',
    statistics: 'Uhari',
    profile: 'Mwihari',
    logout: 'Toka',
    orderNumber: 'Namba ya Oda',
    status: 'Mambo',
    seller: 'Muuza',
    rider: 'Muthoni',
    fee: 'Ugabia',
    distance: 'Umbali',
    actions: 'Mirundo',
    accept: 'Tikia',
    chat: 'Guthura',
    track: 'Kufuatilia',
    pending: 'Iri',
    accepted: 'Imekiririwa',
    inTransit: 'Iri',
    delivered: 'Imewa',
    cancelled: 'Imefunguliwa',
    totalOrders: 'Jumla ya Oda',
    completedOrders: 'Oda Ahari',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hauko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya Kifurushi',
    packageWeight: 'Uzito wa Kifurushi',
    deliveryFee: 'Ugabia',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya Malipo',
    specialInstructions: 'Maagizo ya Ziada',
    standard: 'Ya Kawaida',
    express: 'Ya Haraka',
    urgent: 'Ya Dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya Gari',
    serviceArea: 'Eneo la Huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya Wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda Ahari',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hauko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua Pepe',
    phone: 'Namba ya Simu',
    userType: 'Aina ya Mtumia',
    businessName: 'Jina la Biashara',
    businessLocation: 'Eneo la Biashara',
    riderType: 'Aina ya Mpanda',
    area: 'Eneo la Huduma',
    changePassword: 'Badilisha Nenosiri',
    changeLanguage: 'Badilisha Lugha',
    editProfile: 'Hariri Wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya Faragha',
    terms: 'Masharti ya Huduma'
  },

  // Luo
  luo: {
    dashboard: 'Dwala',
    welcome: 'Wadhi',
    availableOrders: 'Oda Mar Achiel',
    myOrders: 'Oda Ang\'o',
    statistics: 'Ngeko',
    profile: 'Mambo',
    logout: 'Donyo',
    orderNumber: 'Namba ya Oda',
    status: 'Mambo',
    seller: 'Muuza',
    rider: 'Muthoni',
    fee: 'Ugabia',
    distance: 'Umbali',
    actions: 'Mirundo',
    accept: 'Tik',
    chat: 'Mawadri',
    track: 'Kufuatilia',
    pending: 'Iri',
    accepted: 'Imekiririwa',
    inTransit: 'Iri',
    delivered: 'Imewa',
    cancelled: 'Imefunguliwa',
    totalOrders: 'Jumla ya Oda',
    completedOrders: 'Oda Mar Achiel',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hauko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya Kifurushi',
    packageWeight: 'Uzito wa Kifurushi',
    deliveryFee: 'Ugabia',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya Malipo',
    specialInstructions: 'Maagizo ya Ziada',
    standard: 'Ya Kawaida',
    express: 'Ya Haraka',
    urgent: 'Ya Dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya Gari',
    serviceArea: 'Eneo la Huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya Wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda Mar Achiel',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hauko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua Pepe',
    phone: 'Namba ya Simu',
    userType: 'Aina ya Mtumia',
    businessName: 'Jina la Biashara',
    businessLocation: 'Eneo la Biashara',
    riderType: 'Aina ya Mpanda',
    area: 'Eneo la Huduma',
    changePassword: 'Badilisha Nenosiri',
    changeLanguage: 'Badilisha Lugha',
    editProfile: 'Hariri Wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya Faragha',
    terms: 'Masharti ya Huduma'
  },

  // Kamba
  kam: {
    dashboard: 'Thome',
    welcome: 'Nîkî',
    availableOrders: 'Oda zîp',
    myOrders: 'Oda zâng',
    statistics: 'Makwambirî',
    profile: 'Mwîndo',
    logout: 'Toka',
    orderNumber: 'Namba ya oda',
    status: 'Mambo',
    seller: 'Mûthî',
    rider: 'Mûthî',
    fee: 'Mûka',
    distance: 'Gukano',
    actions: 'Matendo',
    accept: 'Tangîza',
    chat: 'Mawadîri',
    track: 'Kûta',
    pending: 'Inasubiri',
    accepted: 'Imekirîwa',
    inTransit: 'Inaendelea',
    delivered: 'Imewa',
    cancelled: 'Imefungûla',
    totalOrders: 'Jumla ya oda',
    completedOrders: 'Oda zîp',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hayuko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya kifurushi',
    packageWeight: 'Uzito wa kifurushi',
    deliveryFee: 'Ada ya kuleta',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya malipo',
    specialInstructions: 'Maagizo ya ziada',
    standard: 'Ya kawaida',
    express: 'Ya haraka',
    urgent: 'Ya dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya gari',
    serviceArea: 'Eneo la huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda zîp',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hayuko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua pepe',
    phone: 'Namba ya simu',
    userType: 'Aina ya mtumia',
    businessName: 'Jina la biashara',
    businessLocation: 'Eneo la biashara',
    riderType: 'Aina ya mpanda',
    area: 'Eneo la huduma',
    changePassword: 'Badilisha nenosiri',
    changeLanguage: 'Badilisha lugha',
    editProfile: 'Hariri wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya faragha',
    terms: 'Masharti ya huduma'
  },

  // Meru
  mer: {
    dashboard: 'Thome',
    welcome: 'Nîkî',
    availableOrders: 'Oda zîp',
    myOrders: 'Oda zâng',
    statistics: 'Makwambirî',
    profile: 'Mwîndo',
    logout: 'Toka',
    orderNumber: 'Namba ya oda',
    status: 'Mambo',
    seller: 'Mûthî',
    rider: 'Mûthî',
    fee: 'Mûka',
    distance: 'Gukano',
    actions: 'Matendo',
    accept: 'Tangîza',
    chat: 'Mawadîri',
    track: 'Kûta',
    pending: 'Inasubiri',
    accepted: 'Imekirîwa',
    inTransit: 'Inaendelea',
    delivered: 'Imewa',
    cancelled: 'Imefungûla',
    totalOrders: 'Jumla ya oda',
    completedOrders: 'Oda zîp',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hayuko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya kifurushi',
    packageWeight: 'Uzito wa kifurushi',
    deliveryFee: 'Ada ya kuleta',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya malipo',
    specialInstructions: 'Maagizo ya ziada',
    standard: 'Ya kawaida',
    express: 'Ya haraka',
    urgent: 'Ya dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya gari',
    serviceArea: 'Eneo la huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda zîp',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hayuko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua pepe',
    phone: 'Namba ya simu',
    userType: 'Aina ya mtumia',
    businessName: 'Jina la biashara',
    businessLocation: 'Eneo la biashara',
    riderType: 'Aina ya mpanda',
    area: 'Eneo la huduma',
    changePassword: 'Badilisha nenosiri',
    changeLanguage: 'Badilisha lugha',
    editProfile: 'Hariri wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya faragha',
    terms: 'Masharti ya huduma'
  },

  // Taita/Taveta
  te: {
    dashboard: 'Thome',
    welcome: 'Nîkî',
    availableOrders: 'Oda zîp',
    myOrders: 'Oda zâng',
    statistics: 'Makwambirî',
    profile: 'Mwîndo',
    logout: 'Toka',
    orderNumber: 'Namba ya oda',
    status: 'Mambo',
    seller: 'Mûthî',
    rider: 'Mûthî',
    fee: 'Mûka',
    distance: 'Gukano',
    actions: 'Matendo',
    accept: 'Tangîza',
    chat: 'Mawadîri',
    track: 'Kûta',
    pending: 'Inasubiri',
    accepted: 'Imekirîwa',
    inTransit: 'Inaendelea',
    delivered: 'Imewa',
    cancelled: 'Imefungûla',
    totalOrders: 'Jumla ya oda',
    completedOrders: 'Oda zîp',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hayuko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya kifurushi',
    packageWeight: 'Uzito wa kifurushi',
    deliveryFee: 'Ada ya kuleta',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya malipo',
    specialInstructions: 'Maagizo ya ziada',
    standard: 'Ya kawaida',
    express: 'Ya haraka',
    urgent: 'Ya dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya gari',
    serviceArea: 'Eneo la huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda zîp',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hayuko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua pepe',
    phone: 'Namba ya simu',
    userType: 'Aina ya mtumia',
    businessName: 'Jina la biashara',
    businessLocation: 'Eneo la biashara',
    riderType: 'Aina ya mpanda',
    area: 'Eneo la huduma',
    changePassword: 'Badilisha nenosiri',
    changeLanguage: 'Badilisha lugha',
    editProfile: 'Hariri wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya faragha',
    terms: 'Masharti ya huduma'
  },

  // Ewe
  ewe: {
    dashboard: 'Thome',
    welcome: 'Nîkî',
    availableOrders: 'Oda zîp',
    myOrders: 'Oda zâng',
    statistics: 'Makwambirî',
    profile: 'Mwîndo',
    logout: 'Toka',
    orderNumber: 'Namba ya oda',
    status: 'Mambo',
    seller: 'Mûthî',
    rider: 'Mûthî',
    fee: 'Mûka',
    distance: 'Gukano',
    actions: 'Matendo',
    accept: 'Tangîza',
    chat: 'Mawadîri',
    track: 'Kûta',
    pending: 'Inasubiri',
    accepted: 'Imekirîwa',
    inTransit: 'Inaendelea',
    delivered: 'Imewa',
    cancelled: 'Imefungûla',
    totalOrders: 'Jumla ya oda',
    completedOrders: 'Oda zîp',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hayuko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya kifurushi',
    packageWeight: 'Uzito wa kifurushi',
    deliveryFee: 'Ada ya kuleta',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya malipo',
    specialInstructions: 'Maagizo ya ziada',
    standard: 'Ya kawaida',
    express: 'Ya haraka',
    urgent: 'Ya dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya gari',
    serviceArea: 'Eneo la huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda zîp',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hayuko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua pepe',
    phone: 'Namba ya simu',
    userType: 'Aina ya mtumia',
    businessName: 'Jina la biashara',
    businessLocation: 'Eneo la biashara',
    riderType: 'Aina ya mpanda',
    area: 'Eneo la huduma',
    changePassword: 'Badilisha nenosiri',
    changeLanguage: 'Badilisha lugha',
    editProfile: 'Hariri wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya faragha',
    terms: 'Masharti ya huduma'
  },

  // Pokomo
  pk: {
    dashboard: 'Thome',
    welcome: 'Nîkî',
    availableOrders: 'Oda zîp',
    myOrders: 'Oda zâng',
    statistics: 'Makwambirî',
    profile: 'Mwîndo',
    logout: 'Toka',
    orderNumber: 'Namba ya oda',
    status: 'Mambo',
    seller: 'Mûthî',
    rider: 'Mûthî',
    fee: 'Mûka',
    distance: 'Gukano',
    actions: 'Matendo',
    accept: 'Tangîza',
    chat: 'Mawadîri',
    track: 'Kûta',
    pending: 'Inasubiri',
    accepted: 'Imekirîwa',
    inTransit: 'Inaendelea',
    delivered: 'Imewa',
    cancelled: 'Imefungûla',
    totalOrders: 'Jumla ya oda',
    completedOrders: 'Oda zîp',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hayuko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya kifurushi',
    packageWeight: 'Uzito wa kifurushi',
    deliveryFee: 'Ada ya kuleta',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya malipo',
    specialInstructions: 'Maagizo ya ziada',
    standard: 'Ya kawaida',
    express: 'Ya haraka',
    urgent: 'Ya dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya gari',
    serviceArea: 'Eneo la huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda zîp',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hayuko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua pepe',
    phone: 'Namba ya simu',
    userType: 'Aina ya mtumia',
    businessName: 'Jina la biashara',
    businessLocation: 'Eneo la biashara',
    riderType: 'Aina ya mpanda',
    area: 'Eneo la huduma',
    changePassword: 'Badilisha nenosiri',
    changeLanguage: 'Badilisha lugha',
    editProfile: 'Hariri wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya faragha',
    terms: 'Masharti ya huduma'
  },

  // Giriama
  gi: {
    dashboard: 'Thome',
    welcome: 'Nîkî',
    availableOrders: 'Oda zîp',
    myOrders: 'Oda zâng',
    statistics: 'Makwambirî',
    profile: 'Mwîndo',
    logout: 'Toka',
    orderNumber: 'Namba ya oda',
    status: 'Mambo',
    seller: 'Mûthî',
    rider: 'Mûthî',
    fee: 'Mûka',
    distance: 'Gukano',
    actions: 'Matendo',
    accept: 'Tangîza',
    chat: 'Mawadîri',
    track: 'Kûta',
    pending: 'Inasubiri',
    accepted: 'Imekirîwa',
    inTransit: 'Inaendelea',
    delivered: 'Imewa',
    cancelled: 'Imefungûla',
    totalOrders: 'Jumla ya oda',
    completedOrders: 'Oda zîp',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hayuko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya kifurushi',
    packageWeight: 'Uzito wa kifurushi',
    deliveryFee: 'Ada ya kuleta',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya malipo',
    specialInstructions: 'Maagizo ya ziada',
    standard: 'Ya kawaida',
    express: 'Ya haraka',
    urgent: 'Ya dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya gari',
    serviceArea: 'Eneo la huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda zîp',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hayuko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua pepe',
    phone: 'Namba ya simu',
    userType: 'Aina ya mtumia',
    businessName: 'Jina la biashara',
    businessLocation: 'Eneo la biashara',
    riderType: 'Aina ya mpanda',
    area: 'Eneo la huduma',
    changePassword: 'Badilisha nenosiri',
    changeLanguage: 'Badilisha lugha',
    editProfile: 'Hariri wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya faragha',
    terms: 'Masharti ya huduma'
  },

  // Kuria
  ku: {
    dashboard: 'Thome',
    welcome: 'Nîkî',
    availableOrders: 'Oda zîp',
    myOrders: 'Oda zâng',
    statistics: 'Makwambirî',
    profile: 'Mwîndo',
    logout: 'Toka',
    orderNumber: 'Namba ya oda',
    status: 'Mambo',
    seller: 'Mûthî',
    rider: 'Mûthî',
    fee: 'Mûka',
    distance: 'Gukano',
    actions: 'Matendo',
    accept: 'Tangîza',
    chat: 'Mawadîri',
    track: 'Kûta',
    pending: 'Inasubiri',
    accepted: 'Imekirîwa',
    inTransit: 'Inaendelea',
    delivered: 'Imewa',
    cancelled: 'Imefungûla',
    totalOrders: 'Jumla ya oda',
    completedOrders: 'Oda zîp',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hayuko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya kifurushi',
    packageWeight: 'Uzito wa kifurushi',
    deliveryFee: 'Ada ya kuleta',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya malipo',
    specialInstructions: 'Maagizo ya ziada',
    standard: 'Ya kawaida',
    express: 'Ya haraka',
    urgent: 'Ya dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya gari',
    serviceArea: 'Eneo la huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda zîp',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hayuko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua pepe',
    phone: 'Namba ya simu',
    userType: 'Aina ya mtumia',
    businessName: 'Jina la biashara',
    businessLocation: 'Eneo la biashara',
    riderType: 'Aina ya mpanda',
    area: 'Eneo la huduma',
    changePassword: 'Badilisha nenosiri',
    changeLanguage: 'Badilisha lugha',
    editProfile: 'Hariri wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya faragha',
    terms: 'Masharti ya huduma'
  },

  // Mijikenda
  km: {
    dashboard: 'Thome',
    welcome: 'Nîkî',
    availableOrders: 'Oda zîp',
    myOrders: 'Oda zâng',
    statistics: 'Makwambirî',
    profile: 'Mwîndo',
    logout: 'Toka',
    orderNumber: 'Namba ya oda',
    status: 'Mambo',
    seller: 'Mûthî',
    rider: 'Mûthî',
    fee: 'Mûka',
    distance: 'Gukano',
    actions: 'Matendo',
    accept: 'Tangîza',
    chat: 'Mawadîri',
    track: 'Kûta',
    pending: 'Inasubiri',
    accepted: 'Imekirîwa',
    inTransit: 'Inaendelea',
    delivered: 'Imewa',
    cancelled: 'Imefungûla',
    totalOrders: 'Jumla ya oda',
    completedOrders: 'Oda zîp',
    averageRating: 'Wastani',
    earnings: 'Mapato',
    availability: 'Weku',
    available: 'Yuko',
    unavailable: 'Hayuko',
    pickupLocation: 'Eneo la Kupokelea',
    deliveryLocation: 'Eneo la Kuleta',
    packageDescription: 'Maelezo ya kifurushi',
    packageWeight: 'Uzito wa kifurushi',
    deliveryFee: 'Ada ya kuleta',
    priority: 'Kipaumlevu',
    paymentMethod: 'Njia ya malipo',
    specialInstructions: 'Maagizo ya ziada',
    standard: 'Ya kawaida',
    express: 'Ya haraka',
    urgent: 'Ya dharura',
    cash: 'Pesa',
    mpesa: 'M-Pesa',
    card: 'Kadi',
    motorcycle: 'Baiskeli',
    driver: 'Dereva',
    vehicleNumber: 'Namba ya gari',
    serviceArea: 'Eneo la huduma',
    averageRating: 'Wastani',
    totalRatings: 'Jumla ya wastani',
    credibilityScore: 'Alama',
    completedDeliveries: 'Oda zîp',
    totalEarnings: 'Mapato',
    online: 'Yuko',
    offline: 'Hayuko',
    lastSeen: 'Ulionekewa',
    name: 'Jina',
    email: 'Barua pepe',
    phone: 'Namba ya simu',
    userType: 'Aina ya mtumia',
    businessName: 'Jina la biashara',
    businessLocation: 'Eneo la biashara',
    riderType: 'Aina ya mpanda',
    area: 'Eneo la huduma',
    changePassword: 'Badilisha nenosiri',
    changeLanguage: 'Badilisha lugha',
    editProfile: 'Hariri wasifu',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    help: 'Msaada',
    about: 'Kuhusu',
    contact: 'Wasiliana',
    privacy: 'Sera ya faragha',
    terms: 'Masharti ya huduma'
  },

  // Other minor languages
  de: { // German (for completeness)
    dashboard: 'Dashboard',
    welcome: 'Willkommen zurück',
    availableOrders: 'Verfügbare Bestellungen',
    myOrders: 'Meine Bestellungen',
    statistics: 'Statistiken',
    profile: 'Profil',
    logout: 'Abmelden',
    orderNumber: 'Bestellnummer',
    status: 'Status',
    seller: 'Verkäufer',
    rider: 'Fahrer',
    fee: 'Gebühr',
    distance: 'Entfernung',
    actions: 'Aktionen',
    accept: 'Annehmen',
    chat: 'Chat',
    track: 'Verfolgen',
    pending: 'Ausstehend',
    accepted: 'Angenommen',
    inTransit: 'Unterwegs',
    delivered: 'Geliefert',
    cancelled: 'Storniert',
    totalOrders: 'Gesamtbestellungen',
    completedOrders: 'Abgeschlossene Bestellungen',
    averageRating: 'Durchschnittliche Bewertung',
    earnings: 'Gesamteinnahmen',
    availability: 'Verfügbarkeit',
    available: 'Verfügbar',
    unavailable: 'Nicht verfügbar',
    pickupLocation: 'Abholort',
    deliveryLocation: 'Lieferort',
    packageDescription: 'Paketbeschreibung',
    packageWeight: 'Paketgewicht',
    deliveryFee: 'Liefergebühr',
    priority: 'Priorität',
    paymentMethod: 'Zahlungsmethode',
    specialInstructions: 'Besondere Anweisungen',
    standard: 'Standard',
    express: 'Express',
    urgent: 'Dringend',
    cash: 'Bar',
    mpesa: 'M-Pesa',
    card: 'Kreditkarte',
    motorcycle: 'Motorrad',
    driver: 'Fahrer',
    vehicleNumber: 'Fahrzeugkennzeichen',
    serviceArea: 'Servicebereich',
    averageRating: 'Durchschnittliche Bewertung',
    totalRatings: 'Gesamtbewertungen',
    credibilityScore: 'Glaubwürdigkeitswert',
    completedDeliveries: 'Abgeschlossene Lieferungen',
    totalEarnings: 'Gesamteinnahmen',
    online: 'Online',
    offline: 'Offline',
    lastSeen: 'Zuletzt gesehen',
    name: 'Name',
    email: 'E-Mail',
    phone: 'Telefon',
    userType: 'Benutzertyp',
    businessName: 'Geschäftsname',
    businessLocation: 'Geschäftstandort',
    riderType: 'Fahrertyp',
    area: 'Bereich',
    changePassword: 'Passwort ändern',
    changeLanguage: 'Sprache ändern',
    editProfile: 'Profil bearbeiten',
    notifications: 'Benachrichtigungen',
    settings: 'Einstellungen',
    help: 'Hilfe',
    about: 'Über',
    contact: 'Kontakt',
    privacy: 'Datenschutzerklärung',
    terms: 'Nutzungsbedingungen'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get saved language from localStorage
    const savedLanguage = localStorage.getItem('preferredLanguage') || 'en';
    return savedLanguage;
  });

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('preferredLanguage', newLanguage);
    
    // Update user preference in database (if logged in)
    const userData = localStorage.getItem('user');
    if (userData) {
      const userId = JSON.parse(userData).id;
      // This would update the user's language preference in the database
      // Implementation would depend on your auth system
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
